/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SomeClassTest {
    @Test
    public void appHasAGreeting() {
        var expected = 5;
        var actual = SomeClass.sum(3, 2);
        assertEquals(expected, actual);
    }
}
