/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet;

public class SomeClass {

    public static int sum(int num1, int num2) {
        return num1 + num2;
    }
}
